version: '3'
services:
  db:
    image: mariadb
    restart: on-failure
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_bankupp_dev:/var/lib/mysql
      - ./config/database/:/database/
    environment:
      MARIADB_ROOT_PASSWORD: passwd
      MARIADB_DATABASE: bankupp
    ports:
      - "3306:3306"
volumes:
  db_bankupp_dev: